default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: requests_trap_development

test:
  <<: *default
  database: requests_trap_test

production:
  <<: *default
  database: requests_trap_production
  username: requests_trap
  password: <%= ENV['REQUESTS_TRAP_DATABASE_PASSWORD'] %>
